# Generated by Django 4.2.4 on 2023-08-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hash_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
