# Generated by Django 4.2.4 on 2023-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_hash_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
